name: cancellation_token_hoc081098
description: Dart Cancellation Token. Inspired by CancellationToken in C#. A Dart utility package for easy async task cancellation.
version: 2.0.0
homepage: https://github.com/hoc081098/cancellation_token_hoc081098.git
repository: https://github.com/hoc081098/cancellation_token_hoc081098.git
issue_tracker: https://github.com/hoc081098/cancellation_token_hoc081098/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: ^3.0.0

topics:
  - hoc081098
  - reactive-programming
  - cancel-token
  - cancellation-token
  - cancellation

dependencies:
  rxdart_ext: ^0.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5

